spring.application.name=kinlarb-management-service
spring.profiles.active=dev

# Stop converting camelCase to snake_case (e.g. marginPercent -> margin_percent)
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
