spring.application.name=kinlarb-management-service

# Database Connection (PostgreSQL from Docker Compose)
spring.datasource.url=jdbc:postgresql://localhost:5432/kinlarb_db
spring.datasource.username=kinlarb_dev
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Stop converting camelCase to snake_case (e.g. marginPercent -> margin_percent)
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Docker Compose Path
spring.docker.compose.file=src/main/resources/docker-compose.yml
