# Database Connection (Production)
spring.datasource.url=jdbc:postgresql://localhost:5432/kinlarb_db_prod
spring.datasource.username=kinlarb_prod
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
